// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TutoringCenterManagement.Data;

#nullable disable

namespace TutoringCenterManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260309183515_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AccountId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("AttendanceId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LastUpdatedBy");

                    b.HasIndex("StudentId");

                    b.HasIndex("SessionId", "StudentId")
                        .IsUnique();

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GradeLevel")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Subject")
                        .HasColumnType("int");

                    b.HasKey("ClassId");

                    b.HasIndex("ClassCode")
                        .IsUnique();

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.ClassStudent", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateOnly?>("LeftAt")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartedAt")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ClassId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("ClassStudents");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Holiday", b =>
                {
                    b.Property<int>("HolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HolidayId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("HolidayId");

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("Holidays", t =>
                        {
                            t.HasCheckConstraint("CK_Holiday_DateRange", "[EndDate] >= [StartDate]");
                        });
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Parent", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("AccountId");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomCode")
                        .IsUnique();

                    b.ToTable("Rooms", t =>
                        {
                            t.HasCheckConstraint("CK_Room_Capacity", "[Capacity] > 0");
                        });
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherAssistantId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.HasIndex("ClassId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SessionDate");

                    b.HasIndex("ShiftId");

                    b.HasIndex("TeacherAssistantId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("ShiftId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Staff", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AccountId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Student", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentSchool")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("AccountId");

                    b.HasIndex("ParentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Teacher", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("AccountId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.TeacherSubject", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("Subject")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("TeacherId", "Subject");

                    b.ToTable("TeacherSubjects");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.WeeklyScheduleTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherAssistantId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("TemplateId");

                    b.HasIndex("ClassId");

                    b.HasIndex("RoomId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("TeacherAssistantId");

                    b.HasIndex("TeacherId");

                    b.ToTable("WeeklyScheduleTemplates");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Attendance", b =>
                {
                    b.HasOne("TutoringCenterManagement.Data.Entities.Account", "CreatedByAccount")
                        .WithMany("CreatedAttendances")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TutoringCenterManagement.Data.Entities.Account", "LastUpdatedByAccount")
                        .WithMany("LastUpdatedAttendances")
                        .HasForeignKey("LastUpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TutoringCenterManagement.Data.Entities.Session", "Session")
                        .WithMany("Attendances")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutoringCenterManagement.Data.Entities.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByAccount");

                    b.Navigation("LastUpdatedByAccount");

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.ClassStudent", b =>
                {
                    b.HasOne("TutoringCenterManagement.Data.Entities.Class", "Class")
                        .WithMany("ClassStudents")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutoringCenterManagement.Data.Entities.Student", "Student")
                        .WithMany("ClassStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Parent", b =>
                {
                    b.HasOne("TutoringCenterManagement.Data.Entities.Account", "Account")
                        .WithOne("Parent")
                        .HasForeignKey("TutoringCenterManagement.Data.Entities.Parent", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Session", b =>
                {
                    b.HasOne("TutoringCenterManagement.Data.Entities.Class", "Class")
                        .WithMany("Sessions")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TutoringCenterManagement.Data.Entities.Room", "Room")
                        .WithMany("Sessions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TutoringCenterManagement.Data.Entities.Shift", "Shift")
                        .WithMany("Sessions")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TutoringCenterManagement.Data.Entities.Teacher", "TeacherAssistant")
                        .WithMany("AssistantSessions")
                        .HasForeignKey("TeacherAssistantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TutoringCenterManagement.Data.Entities.Teacher", "Teacher")
                        .WithMany("Sessions")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TutoringCenterManagement.Data.Entities.WeeklyScheduleTemplate", "Template")
                        .WithMany("Sessions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Class");

                    b.Navigation("Room");

                    b.Navigation("Shift");

                    b.Navigation("Teacher");

                    b.Navigation("TeacherAssistant");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Staff", b =>
                {
                    b.HasOne("TutoringCenterManagement.Data.Entities.Account", "Account")
                        .WithOne("Staff")
                        .HasForeignKey("TutoringCenterManagement.Data.Entities.Staff", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Student", b =>
                {
                    b.HasOne("TutoringCenterManagement.Data.Entities.Account", "Account")
                        .WithOne("Student")
                        .HasForeignKey("TutoringCenterManagement.Data.Entities.Student", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutoringCenterManagement.Data.Entities.Parent", "Parent")
                        .WithMany("Students")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Account");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Teacher", b =>
                {
                    b.HasOne("TutoringCenterManagement.Data.Entities.Account", "Account")
                        .WithOne("Teacher")
                        .HasForeignKey("TutoringCenterManagement.Data.Entities.Teacher", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.TeacherSubject", b =>
                {
                    b.HasOne("TutoringCenterManagement.Data.Entities.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.WeeklyScheduleTemplate", b =>
                {
                    b.HasOne("TutoringCenterManagement.Data.Entities.Class", "Class")
                        .WithMany("WeeklyScheduleTemplates")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutoringCenterManagement.Data.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TutoringCenterManagement.Data.Entities.Shift", "Shift")
                        .WithMany("WeeklyScheduleTemplates")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TutoringCenterManagement.Data.Entities.Teacher", "TeacherAssistant")
                        .WithMany("AssistantTemplates")
                        .HasForeignKey("TeacherAssistantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TutoringCenterManagement.Data.Entities.Teacher", "Teacher")
                        .WithMany("Templates")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Room");

                    b.Navigation("Shift");

                    b.Navigation("Teacher");

                    b.Navigation("TeacherAssistant");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Account", b =>
                {
                    b.Navigation("CreatedAttendances");

                    b.Navigation("LastUpdatedAttendances");

                    b.Navigation("Parent");

                    b.Navigation("Staff");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Class", b =>
                {
                    b.Navigation("ClassStudents");

                    b.Navigation("Sessions");

                    b.Navigation("WeeklyScheduleTemplates");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Parent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Room", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Session", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Shift", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("WeeklyScheduleTemplates");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("ClassStudents");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.Teacher", b =>
                {
                    b.Navigation("AssistantSessions");

                    b.Navigation("AssistantTemplates");

                    b.Navigation("Sessions");

                    b.Navigation("TeacherSubjects");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("TutoringCenterManagement.Data.Entities.WeeklyScheduleTemplate", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
